from . import start
from . import admin
from . import menuhandler
from . import shaharhandler
from . import payat
from . import poklanishhen
from . import namozerkaklarh
from . import namozayolh
from . import quronarb
from . import quronuzb
from . import allahningismlarii
from . import beshfarzh
from . import maruzah
from . import Qiblah
from . import help