from . import menu
from . import namozm
from . import namozjanaza
from . import namozjamo
from . import poklanish
from . import foydali
from . import quron
from . import quranuz
from . import quronm
from . import beshfarz
from . import allahningismlari
from . import namozerkak
from . import namozayol
from . import maruza
from . import adminKeyboard