from aiogram.types import ReplyKeyboardMarkup, KeyboardButton

Allahningismlari = ReplyKeyboardMarkup(
    keyboard=[
        [
            KeyboardButton(text="Alloh"),
            KeyboardButton(text="Ar-Rohmān"),
            KeyboardButton(text="Ar-Rohīm"),
        ],
       [
       		KeyboardButton(text="Al-Malik"),
       	KeyboardButton(text="Al-Quddūs"),
       	KeyboardButton(text="As-Salām"),
       ],
      [
      	KeyboardButton(text="Al-Mu’min"),
      	KeyboardButton(text="Al-Muhaymin"),
      	KeyboardButton(text="Al-Aziz"),
       ],
       [
       KeyboardButton(text="Al-Jabbār"),
      	KeyboardButton(text="Al-Mutakabbir"),
      	KeyboardButton(text="Al-Holiq"),
       ],
       [
       	KeyboardButton(text="Al-Bāri"),
      	KeyboardButton(text="Al-Musovvir"),
      	KeyboardButton(text="Al-Gʻoffār"),
       ],
       [
       	KeyboardButton(text="Al-Qohhār"),
      	KeyboardButton(text="Al-Vahhāb"),
      	KeyboardButton(text="Ar-Rozzāq"),
       ],
       [
       	KeyboardButton(text="Al-Fattāh"),
      	KeyboardButton(text="Al-'Alīm"),
      	KeyboardButton(text="Al-Qobiz"),
       ],
       [
       	KeyboardButton(text="Al-Bāsit"),
      	KeyboardButton(text="Al-Hofiz"),
      	KeyboardButton(text="Ar-Rāfi"),
       ],
       [
       	KeyboardButton(text="Al-Mu’izz"),
      	KeyboardButton(text="Al-Muzill"),
      	KeyboardButton(text="As-Samī"),
       ],
       [
       	KeyboardButton(text="Al-Basīr"),
      	KeyboardButton(text="Al-Hakam"),
      	KeyboardButton(text="Al-Adl"),
       ],
       [
       	KeyboardButton(text="Al-Latīf"),
      	KeyboardButton(text="Al-Hobīr"),
      	KeyboardButton(text="Al-Halīm"),
       ],
       [
       	KeyboardButton(text="Al-'Azīm"),
      	KeyboardButton(text="Al-Gʻofūr"),
      	KeyboardButton(text="Ash-Shakūr"),
       ],
       [
       	KeyboardButton(text="Al-'Aliyy"),
      	KeyboardButton(text="Al-Kabīr"),
      	KeyboardButton(text="Al-Hafīz"),
       ],
       [
       	KeyboardButton(text="Al-Muqīt"),
      	KeyboardButton(text="An-Hasīb"),
      	KeyboardButton(text="Al-Jalīl"),
       ],
       [
       	KeyboardButton(text="Al-Karīm"),
      	KeyboardButton(text="Ar-Roqīb"),
      	KeyboardButton(text="Al-Mujīb"),
       ],
       [
       	KeyboardButton(text="Al-Vāsi"),
      	KeyboardButton(text="Al-Hakīm"),
      	KeyboardButton(text="Al-Vadūd"),
       ],
       [
       	KeyboardButton(text="Al-Majīd"),
      	KeyboardButton(text="Al-Bā'is"),
      	KeyboardButton(text="Ash-Shahīd"),
       ],
       [
       	KeyboardButton(text="Al-Haqq"),
      	KeyboardButton(text="Al-Vakīl"),
      	KeyboardButton(text="Al-Qovviyy"),
       ],
       [
       	KeyboardButton(text="Al-Matīn"),
      	KeyboardButton(text="Al-Valiyy"),
      	KeyboardButton(text="Al-Hamīd"),
       ],
       [
       	KeyboardButton(text="Al-Muhsi"),
      	KeyboardButton(text="Al-Mubdi"),
      	KeyboardButton(text="Al-Mu'īd"),
       ],
       [
       	KeyboardButton(text="Al-Muhyi"),
      	KeyboardButton(text="Al-Mumīt"),
      	KeyboardButton(text="Al-Hayy"),
       ],
       [
       	KeyboardButton(text="Al-Qoyyūm"),
      	KeyboardButton(text="Al-Vājid"),
      	KeyboardButton(text="Al-Mājid"),
       ],
       [
       	KeyboardButton(text="Al-Vāhid"),
      	KeyboardButton(text="As-Somad"),
      	KeyboardButton(text="Al-Qodir"),
       ],
       [
       	KeyboardButton(text="Al-Muqtadir"),
      	KeyboardButton(text="Al-Muqoddim"),
      	KeyboardButton(text="Al-Mu'ahhir"),
       ],
       [
       	KeyboardButton(text="Al-'Avval"),
      	KeyboardButton(text="Al-'Ahir"),
      	KeyboardButton(text="Az-Zohir"),
       ],
       [
       	KeyboardButton(text="Al-Bātin"),
      	KeyboardButton(text="Al-Vāli"),
      	KeyboardButton(text="Al-Mutā'ali"),
       ],
       [
       	KeyboardButton(text="Al-Barr"),
      	KeyboardButton(text="At-Tavvāb"),
      	KeyboardButton(text="Al-Muntaqim"),
       ],
       [
       	KeyboardButton(text="Al-Afuvv"),
      	KeyboardButton(text="Ar-Roʻūf"),
      	KeyboardButton(text="Mālik-ul-Mulik"),
       ],
       [
       	KeyboardButton(text="Zūl-Jalāli-Val'ikrom"),
      	KeyboardButton(text="Al-Muqsiţ"),
      	KeyboardButton(text="Al-Jāmi"),
       ],
       [
       	KeyboardButton(text="Al-Gʻoni"),
      	KeyboardButton(text="Al-Mugʻni"),
      	KeyboardButton(text="Al-Māni"),
       ],
       [
       	KeyboardButton(text="Az-Zorr"),
      	KeyboardButton(text="An-Nāfi"),
      	KeyboardButton(text="An-Nūr"),
      ],
      [
      	KeyboardButton(text="Al-Hādi"),
      	KeyboardButton(text="Al-Badī"),
      	KeyboardButton(text="Al-Bāqi"),
      ],
      [
      	KeyboardButton(text="Al-Vāris"),
      	KeyboardButton(text="Ar-Roshīd"),
      	KeyboardButton(text="As-Sobur"),
      ],
      [
       	KeyboardButton(text="Orqaga ➡️"),
        ],
       
    ],
    resize_keyboard=True,
)
